"""changed is_active to integer

Revision ID: 08158a16ea4d
Revises: 5803ba3addde
Create Date: 2024-08-05 13:09:25.597682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '08158a16ea4d'
down_revision: Union[str, None] = '5803ba3addde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('news', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_constraint('ticket_ibfk_3', 'ticket', type_='foreignkey')
    op.create_foreign_key(None, 'ticket', 'routeday', ['day_name'], ['day_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ticket', type_='foreignkey')
    op.create_foreign_key('ticket_ibfk_3', 'ticket', 'routeday', ['day_name'], ['day_name'], ondelete='CASCADE')
    op.alter_column('news', 'is_active',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    # ### end Alembic commands ###
