"""Added disabled to User table

Revision ID: 1fa337f8a2a0
Revises: 0aa9082e4c12
Create Date: 2024-08-02 18:44:39.924356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fa337f8a2a0'
down_revision: Union[str, None] = '0aa9082e4c12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routestation', sa.Column('price', sa.DECIMAL(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routestation', 'price')
    # ### end Alembic commands ###
