"""Updated News table

Revision ID: 3a53e36eb2ec
Revises: b099b69fa065
Create Date: 2024-07-27 14:50:43.442860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3a53e36eb2ec'
down_revision: Union[str, None] = 'b099b69fa065'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('slug', sa.String(length=200), nullable=True))
    op.alter_column('news', 'image',
               existing_type=mysql.VARCHAR(length=300),
               type_=sa.String(length=200),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('news', 'image',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=300),
               existing_nullable=True)
    op.drop_column('news', 'slug')
    # ### end Alembic commands ###
