"""deactivasted -> disabled (defaults to false) in users table

Revision ID: 47dafbc7522a
Revises: 7b9fdafe424d
Create Date: 2024-07-27 15:46:15.302561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '47dafbc7522a'
down_revision: Union[str, None] = '7b9fdafe424d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('disabled', sa.Boolean(), nullable=True))
    op.drop_column('users', 'deactivated')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('deactivated', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('users', 'disabled')
    # ### end Alembic commands ###
