"""Updated user table

Revision ID: 698934fa67ee
Revises: bacd512162bd
Create Date: 2024-07-27 01:55:03.761613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '698934fa67ee'
down_revision: Union[str, None] = 'bacd512162bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('full_name', sa.String(length=35), nullable=True))
    op.drop_column('users', 'lastname')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', mysql.VARCHAR(length=20), nullable=True))
    op.add_column('users', sa.Column('lastname', mysql.VARCHAR(length=35), nullable=True))
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
