"""Dodato active polje u route

Revision ID: 720e2c9cc90c
Revises: 47dafbc7522a
Create Date: 2024-07-28 23:02:05.833668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '720e2c9cc90c'
down_revision: Union[str, None] = '47dafbc7522a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('route', 'is_active')
    # ### end Alembic commands ###
