"""Added deactivated (defaults to True) in users table

Revision ID: 7b9fdafe424d
Revises: 3a53e36eb2ec
Create Date: 2024-07-27 15:11:59.179247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b9fdafe424d'
down_revision: Union[str, None] = '3a53e36eb2ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
