"""Added deactivated to user

Revision ID: b099b69fa065
Revises: c4d56c274738
Create Date: 2024-07-27 14:49:03.511465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b099b69fa065'
down_revision: Union[str, None] = 'c4d56c274738'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('image', sa.String(length=300), nullable=True))
    op.add_column('users', sa.Column('deactivated', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'deactivated')
    op.drop_column('news', 'image')
    # ### end Alembic commands ###
