"""Added latitude and longitude

Revision ID: bacd512162bd
Revises: 8707da1c614d
Create Date: 2024-07-26 00:53:51.827980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bacd512162bd'
down_revision: Union[str, None] = '8707da1c614d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('station', sa.Column(
        'latitude', sa.DECIMAL(precision=10, scale=8), nullable=True))
    op.add_column('station', sa.Column(
        'longitude', sa.DECIMAL(precision=11, scale=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('station', 'longitude')
    op.drop_column('station', 'latitude')
    # ### end Alembic commands ###
