"""added attribute  parent_route to route table

Revision ID: df6b2b7d447f
Revises: be5b25a8acb6
Create Date: 2024-08-04 16:12:35.657731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df6b2b7d447f'
down_revision: Union[str, None] = 'be5b25a8acb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route', sa.Column(
        'price', sa.DECIMAL(precision=5, scale=2), nullable=True))
    op.add_column('route', sa.Column(
        'parent_route', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('route', 'parent_route')
    op.drop_column('route', 'price')
    # ### end Alembic commands ###
