"""foreign key constraint for ticket and routeday

Revision ID: f19849874e11
Revises: 6f24bc7daafb
Create Date: 2024-08-06 20:26:44.120869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f19849874e11'
down_revision: Union[str, None] = '6f24bc7daafb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'ticket', 'routeday', [
                          'company_id', 'day_name', 'route_id'], ['company_id', 'day_name', 'route_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ticket', type_='foreignkey')
    # ### end Alembic commands ###
